FROM debian
ENV HOSTNAME=mrhost         
CMD echo $HOSTNAME

# But: changer la variable d'environnement 

# Construire une image     "docker build -t imagecb ."
# Lancer le l'image        "docker run imagecb"  résultat: 1c2c51db5f97
# Modifier le résulate on veut                   résutat : mrhoste
# Remarque à chaque fois il faut lancer build et run