apiVersion: apps/v1       # Creer un deploiment
kind: Deployment       
metadata:                  # doc: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
  name: nginx-deployment
spec:                       # Deploiment
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:                    # Code
      containers:
      - name: nginx
        image: nginx:1.14.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
