FROM python:3.8-slim

WORKDIR /app

COPY . .              

RUN pip install flask

CMD ["python", "app.py"]    


#"le fichier app.py et le lancer"
#COPY . .  
#"Lancer le code python de l'application"