apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: MTk5NnNhbHV0        # il faut telecharger base64 avant pour encode,
                                # password: 1996 ¨"ctrl Maj P"--> Va nous afficher les fonction base26 encode

